import { useState } from "react";
import type { MouseEventHandler } from "react"
import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "@/components/LazyImage";

// generate simple unique id
const generateId = (): string => {
  return (
    Math.random().toString(36).substring(2, 15) +
    Math.random().toString(36).substring(2, 15)
  );
};

// random number from 1 to 122
const random = () => Math.floor(Math.random() * 122) + 1;

type ImageItem = {
  id: string;
  url: string;
};

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewFox:MouseEventHandler<HTMLButtonElement> = (event) =>{
    const newImagenItem:ImageItem= {
       id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg`
    }

    setImages([
      ...images,
      newImagenItem
    ])
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <button onClick={addNewFox}>Add new fox</button>
        {images.map(({ id, url }, index) => (
          <div className="p-4" key={id}>
            <LazyImage 
                  width={320} 
                  height="auto" 
                  className="rounded bg-gray-300" 
                  title="Random Fox"
                  src={url} 
                  onLazyLoad={(img) => {
                    console.log(`Image #${index + 1} cargada. Nodo:`, img);
                  }}
            />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;